### ISSUE TITLE
v0.3.0 Homebridge crashes on Pairing

### ISSUE THREAD

**Issue by rcoletti116** [jordanryanmoore/homebridge-alexa-player#39]
### Description
When attempting to pair device Homeebridge crashes (sigterm) and restarts. 

### Reproduction Steps
1. Start Homebridge
2. Authenticate plugin
3. Add new devices in Home

### Expected Behavior
Expected behavior is that device will pair and homebridge will not be effected. Actual results is that Homebridge crashes and device never completes pairing.

### Logs
```
[11/24/2020, 15:13:16] TypeError: Cannot read property 'params' of undefined
    at HAPServer._this._handlePairStepOne (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:380:27)
    at HAPServer._this._handlePair (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:362:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

### Additional Context
I'm also still having a general problem with discovery in HK, and the only device that is discovered is my Echo Show. Clicking the "add anyway" to pair is what causes homebridge to crash.

**Comment by jordanryanmoore** [comment]
This seems like something wrong in `HAP-NodeJS` or its `fast-srp-hap ` dependency: https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/HAPServer.ts#L380

**Comment by rcoletti116** [comment]
Only occurs with this plugin.

**Comment by jordanryanmoore** [comment]
Do you have any other plugins where you've had to add external accessories like this before?

**Comment by rcoletti116** [comment]
You’re right. I have had external accessories before, but I just tried to add another one from a different plugin and same results.

**Comment by jordanryanmoore** [comment]
Yeah, something is funky with your Homebridge installation. I would try reinstalling and/or filing a bug with Homebridge directly.

**Comment by rcoletti116** [comment]
For posterity sake -  I did get the crashing issue resolved by running a reinstall of Homebridge.
