### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by MichaelDors** [jordanryanmoore/homebridge-alexa-player#629]
### Description
I'm not sure what's wrong- it just doesn't work.

### Reproduction Steps
1. Get plug-in from official homebridge local website 
2. Set the Amazon domain, homebridge.local, a port. Basically just fill in everything the config wants.
3. Go to that port and login to Amazon
4. It wants a verification code but the page is constantly reloading every few seconds so it's hard to type the code.
5. I finally get the code in and get an Amazon error.

### Expected Behavior
No error on login, no constant reloading, and the devices go in HomeKit.

### Logs

[04/07/2023, 16:41:32] [AlexaPlayer] Failed to initialize. Error: You can try to get the cookie manually by opening http://homebridge.local:2344/ with your browser.
    at /var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/alexa-cookie.js:387:38
    at Server.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-cookie2/lib/proxy.js:368:30)
    at Object.onceWrapper (node:events:627:28)
    at Server.emit (node:events:513:28)
    at emitListeningNT (node:net:1774:10)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)

### Screenshots
![image](https://github.com/BewhiskeredBard/homebridge-alexa-player/assets/115369454/93c8beac-48d5-4cd7-a1ce-5f34acad0f39)

### Additional Context
Running on a rpi

**Comment by MichaelDors** [comment]
Any ideas?

**Comment by drumstix1020** [comment]
I was able to log in, no reloading issue, but beyond that I successfully logged in to see the same "404" page. I thought, maybe this is supposed to happen, and the authentication went through, but I checked the Homebridge logs and there was nothing there from the plugin. Might be broken :/ Praying it's fixable (somebody, anybody, please)

**Comment by MichaelDors** [comment]
> I was able to log in, no reloading issue, but beyond that I successfully logged in to see the same "404" page. I thought, maybe this is supposed to happen, and the authentication went through, but I checked the Homebridge logs and there was nothing there from the plugin. Might be broken :/ Praying it's fixable (somebody, anybody, please)

Yeah, I'm not sure if mine actually logs in or not... I put in my info in and then my 2fa code (as the page is just randomly reloading constantly) but then it jumps to the error. Nothing in the logs for me either.

**Comment by bad-luigi** [comment]
I am also having this issue. Is this still a known bug, or does anyone who if there is a solution?

EDIT: Nevermind, tried a different browser and it worked fine. I recommend using Chrome!
