### ISSUE TITLE
Alexa not showing up

### ISSUE THREAD

**Issue by duckida** [jordanryanmoore/homebridge-alexa-player#635]
### Description
Even with the right cookie, obtained through alexa.amazon.co.uk, I still get the error [30/08/2023, 17:57:31] [AlexaPlayer] Error: Unknown Device or Serial number

### Expected Behavior
The Alexa device would show up as an accessory to pair in Home app.

### Logs
```javascript
[30/08/2023, 17:57:31] [AlexaPlayer] Error: Unknown Device or Serial number
    at AlexaRemote.getMedia (/var/lib/homebridge/node_modules/homebridge-alexa-player/node_modules/alexa-remote2/alexa-remote.js:941:47)
    at /var/lib/homebridge/node_modules/homebridge-alexa-player/src/accessoryFactory.ts:61:24
    at new Promise (<anonymous>)
    at AccessoryFactory.getMedia (/var/lib/homebridge/node_modules/homebridge-alexa-player/src/accessoryFactory.ts:60:16)
    at AccessoryFactory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-player/src/accessoryFactory.ts:28:34)
    at Generator.next (<anonymous>)
    at /var/lib/homebridge/node_modules/homebridge-alexa-player/lib/accessoryFactory.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/var/lib/homebridge/node_modules/homebridge-alexa-player/lib/accessoryFactory.js:4:12)
    at AccessoryFactory.createAccessory (/var/lib/homebridge/node_modules/homebridge-alexa-player/lib/accessoryFactory.js:30:16)
    at /var/lib/homebridge/node_modules/homebridge-alexa-player/src/accessoryFactory.ts:23:37
    at Array.map (<anonymous>)
    at AccessoryFactory.<anonymous> (/var/lib/homebridge/node_modules/homebridge-alexa-player/src/accessoryFactory.ts:23:18)
    at Generator.next (<anonymous>)
    at fulfilled (/var/lib/homebridge/node_modules/homebridge-alexa-player/lib/accessoryFactory.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional Context
ONCE I got it to pair in Home app, but the device said Not Supported (device not supported with Apple Home) and I couldn't use it at all.

**Comment by JanVanOostenrijk** [comment]
Had a similar issue: Tried this plugin a few months ago, removed all the speakers then because of some housekeeping work, now wanting to retry this plugin but none of the speakers showed up except for the one Echo I got since. It seems like Homebridge doesn't unpair accessories cleanly after you remove them from the Home App.

After some digging around, I found the solution:
Even if devices do not show up in the Home App anymore, they're still marked as "paired" within Homebridge. To unpair devices that are no longer paired, in the Homebridge Config UI go to "Homebridge Settings" (three dots-menu on upper right corner), scroll down to "Unpair Bridges / Cameras / TVs / External Accessories" and click the button with an arrow in it on the right. Here, unpair all Echo devices and restart Homebridge. You should be able to see all devices in the "Add Accessory" dialogue in the Home App again.
